var integration = require('./integration/index.js')
  , Package = require('./models/Package.test')
  , middleware = require('./middleware.test')
  , response = require('./response.test')
  , handler = require('./handler.test')
  , style = require('./style.test')
