module.exports.clone = require('./clone')
module.exports.get_deps = require('./get_deps')
module.exports.get_package = require('./get_package')
module.exports.get_tarball = require('./get_tarball')
module.exports.publish = require('./publish')
